In [152]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.impute import SimpleImputer
pd.set_option('display.max_columns', None)

In [153]:
df = pd.read_csv('df18to21_cleaned.csv')

In [154]:
df.head(2)

,Unnamed: 0,sentence_length,year_sentenced,sentence_type,guideline_range,imprisoned,guideline_var_pct,dependents,count_convictons,race,education,disposition,citizen,state,criminal_hist,drug_type,case_type,age,weapon,presentence_stat,gender,crime_type,region,college,white,perc_charged
0,12990,188,2018,1,1.0,1,NaN,1,1,1,1.0,3,1,Utah,1.0,3.0,1.0,24.0,0,1.0,0.0,10,West,0,1,0.079034
1,14616,0,2018,1,NaN,1,NaN,1,1,1,NaN,1,0,Virginia,1.0,NaN,NaN,28.0,0,1.0,0.0,17,South,0,1,0.057644

Strategy for dealing with null values: 

- 'guideline_range' - no need to impute
- 'guideline_var_pct' - no need to impute
- 'criminal_hist' - impute with mode
- 'case_type' - impute with mode
- 'age' - impute with mean
- 'presentence_stat' - no need to impute
- 'gender' - impute with mode

- ‘guideline_range’ - no need to impute
    LETS FILL WITH 0, CREATING NEW CATEGORY FOR SENTENCES OUTSIDE RANGE, WILL BE OHE
- ‘guideline_var_pct’ - no need to impute
    LETS FILL WITH 0, NO DEVIATION FROM GUIDELINES
- ‘guideline_var_mth’ - no need to impute
  LETS FILL WITH 0, NO DEVIATION FROM GUIDELINES

In [187]:
df['age'].fillna(df['age'].mean(), inplace=True)  

df['criminal_hist'].fillna(df['criminal_hist'].mode()[0], inplace=True)    
df['case_type'].fillna(df['case_type'].mode()[0], inplace=True)    
df['gender'].fillna(df['gender'].mode()[0], inplace=True)   

df['drug_type'].fillna(0, inplace=True)
df['presentence_stat'].fillna(1, inplace=True)
df['guideline_range'].fillna(0, inplace=True)
df['guideline_var_pct'].fillna(0, inplace=True)

In [184]:
df.drop(columns='education', inplace=True)

In [189]:
df.to_csv('./NEWSAVE/df18to21_cleaned.csv')

In [190]:
df.head(20)

,Unnamed: 0,sentence_length,year_sentenced,sentence_type,guideline_range,imprisoned,guideline_var_pct,dependents,count_convictons,race,disposition,citizen,state,criminal_hist,drug_type,case_type,age,weapon,presentence_stat,gender,crime_type,region,college,white,perc_charged
0,12990,188,2018,1,1.0,1,0.000000,1,1,1,3,1,Utah,1.0,3.0,1.0,24.0,0,1.0,0.0,10,West,0,1,0.079034
1,14616,0,2018,1,0.0,1,0.000000,1,1,1,1,0,Virginia,1.0,0.0,1.0,28.0,0,1.0,0.0,17,South,0,1,0.057644
2,14617,300,2018,1,6.0,1,0.000000,1,3,1,3,1,North Dakota,1.0,6.0,1.0,41.0,1,1.0,0.0,10,Midwest,0,1,0.148692
3,14619,63,2018,1,1.0,1,0.000000,0,1,2,1,1,Tennessee,1.0,0.0,1.0,25.0,1,1.0,0.0,26,South,0,0,0.074698
4,14620,0,2018,1,2.0,1,0.000000,1,1,1,1,0,Colorado,1.0,0.0,1.0,27.0,0,1.0,0.0,17,West,0,1,0.029711
5,14621,10,2018,1,1.0,1,0.000000,1,1,1,1,0,Texas,1.0,0.0,1.0,26.0,0,1.0,0.0,17,South,0,1,0.231011
6,14622,0,2018,4,1.0,0,0.000000,1,1,1,1,0,Texas,1.0,0.0,1.0,36.0,0,1.0,0.0,17,South,0,1,0.231011
7,14623,0,2018,1,0.0,1,99.625000,1,1,1,1,0,Pennsylvania,1.0,0.0,1.0,26.0,0,1.0,0.0,17,Northeast,0,1,0.039116
8,14624,8,2018,1,0.0,1,55.555556,1,1,1,1,0,California,1.0,0.0,1.0,39.0,0,1.0,0.0,17,West,0,1,0.052463
9,14625,90,2018,1,0.0,1,42.857143,1,1,1,1,1,New Hampshire,1.0,2.0,1.0,30.0,0,1.0,0.0,10,Northeast,1,1,0.053517
10,14626,92,2018,1,1.0,1,0.000000,1,1,1,1,1,Virginia,1.0,0.0,1.0,39.0,0,1.0,0.0,13,South,0,1,0.057644
11,14627,41,2018,1,1.0,1,0.000000,1,1,1,1,1,Idaho,1.0,0.0,1.0,36.0,0,1.0,0.0,13,West,0,1,0.067630
12,14628,90,2018,1,0.0,1,26.760563,0,1,2,1,1,Michigan,1.0,0.0,1.0,21.0,0,1.0,0.0,13,Midwest,0,0,0.039320
13,14676,12,2018,1,0.0,1,42.714286,1,1,1,1,0,Texas,1.0,0.0,1.0,30.0,0,1.0,0.0,17,South,0,1,0.231011
14,14682,188,2018,1,1.0,1,0.000000,0,1,2,1,1,Tennessee,1.0,6.0,1.0,31.0,0,1.0,0.0,10,South,0,0,0.074698
15,14685,27,2018,1,0.0,1,18.181818,1,2,1,1,0,Maryland,1.0,0.0,1.0,53.0,0,2.0,0.0,16,South,0,1,0.039724
16,14687,60,2018,1,0.0,1,60.264901,0,1,1,1,1,Virginia,1.0,3.0,1.0,30.0,0,1.0,1.0,10,South,1,1,0.057644
17,14690,4,2018,2,2.0,1,0.000000,1,1,3,1,1,South Dakota,1.0,6.0,1.0,23.0,0,1.0,0.0,10,Midwest,0,0,0.206605
18,14691,20,2018,1,4.0,1,0.000000,1,1,1,1,0,Texas,1.0,0.0,1.0,42.0,0,1.0,0.0,17,South,0,1,0.231011
19,14692,180,2018,1,3.0,1,0.000000,1,2,1,1,1,Kentucky,1.0,6.0,1.0,53.0,1,1.0,0.0,10,South,0,1,0.065144